apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/crds.yaml
  - base/externalsecret.yaml

helmCharts:
  - repo: https://smallstep.github.io/helm-charts
    name: step-issuer
    version: 1.9.11
    releaseName: step-issuer
    valuesFile: values.yaml
    namespace: step-issuer