apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base

helmCharts:
  - repo: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.12.0
    releaseName: ingress-nginx-public
    valuesFile: ../../base/values.yaml
    namespace: ingress-nginx
    additionalValuesFiles:
      - values.yaml
