apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # Install CRDs first (cluster-scoped, no namespace needed)
  - name: gateway-crds-helm
    version: v1.6.3
    releaseName: gateway-crds-helm
    repo: oci://docker.io/envoyproxy
