apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - base/gatewayclass.yaml
  - base/gateway.yaml

helmCharts:
  # Install Envoy Gateway controller
  - name: gateway-helm
    version: v1.6.3
    releaseName: gateway-helm
    repo: oci://docker.io/envoyproxy
    valuesFile: values.yaml
    namespace: envoy-gateway-system
