apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    version: 0.25.2
    releaseName: redis
    repo: oci://registry-1.docker.io/cloudpirates
    namespace: redis
    valuesFile: values.yaml
